//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Course.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    
        public int ProductId { get; set; }
        
        [Required(ErrorMessage="商品名稱為必填欄位")]
        //加上屬性，前後端驗證同時完成，可把瀏覽器的js停用檢視
        //屬性內可以自訂錯誤訊息，加上ErrorMessage
        public string ProductName { get; set; }

        [Required]
        public Nullable<decimal> Price { get; set; }

        [Required]
        public Nullable<bool> Active { get; set; }

        [Required]
        public Nullable<decimal> Stock { get; set; }
    
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}
